version: "3"
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
      - 5000:5000
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # Add any other volumes or configurations as needed
    networks:
      - app-network

  angular:
    build:
      context: ./Screamer.AngularUI
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - webapi

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA='Y'
      - SA_PASSWORD='yourStrongPassword'
    ports:
      - 1433:1433
networks:
  app-network:
    driver: bridge
