import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CategoryService {

  constructor() { }

  categories: string[] = [
    'News',
    'Politics',
    'Science',
    'Technology',
    'Gaming',
    'Sports',
    'Music',
    'Movies',
    'Television',
    'Books',
    'Art',
    'Food',
    'Travel',
    'Fitness',
    'Health',
    'Fashion',
    'Relationships',
    'Advice',
    'Writing',
    'Photography',
    'DIY (Do-It-Yourself)',
    'Nature',
    'Animals',
    'Memes',
    'Funny',
    'Jokes',
    'History',
    'Philosophy',
    'Psychology',
    'Education',
    'Career',
    'Personal Finance',
    'Entrepreneurship',
    'Parenting',
    'Relationships',
    'Technology News',
    'Programming',
    'Web Development',
    'Data Science',
    'Cryptocurrency',
    'Design',
    'Gaming News',
    'PC Gaming',
    'Console Gaming',
    'Mobile Gaming',
    'Esports',
    'Music News',
    'Hip-Hop',
    'Rock',
    'Pop Culture',
    'Fitness Motivation',
    'Nutrition',
    'Weightlifting',
    'Yoga',
    'Running',
    'Cycling',
    'CrossFit',
    'Bodybuilding',
    'Productivity',
    'Self-improvement',
    'Meditation',
    'Mindfulness',
    'Motivation',
    'Self-care',
    'Cooking',
    'Baking',
    'Grilling',
    'Veganism',
    'Vegetarianism',
    'Meal Prep',
    'Gardening',
    'Home Improvement',
    'Interior Design',
    'Real Estate',
    'Personal Finance Tips',
    'Investing',
    'Stock Market',
    'Cryptocurrency Trading',
    'Entrepreneur Stories',
    'Startups',
    'Small Business',
    'Marketing',
    'Social Media',
    'Podcasts',
    'Writing Prompts',
    'Fantasy',
    'Science Fiction',
    'Horror',
    'Thrillers',
    'True Crime',
    'Paranormal',
    'Comics',
    'Anime',
    'Manga',
    'Board Games',
    'Card Games',
    'Tabletop RPGs',
    'Travel Photography',
    'Outdoor Adventures',
    'Celebrities',
    'nsfw',
  ];

  searchTerm: string = '';
  searchResults: string[] = [];
  addedCategories: string[] = [];
}
