// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Screamer.Presistance.DatabaseContext;

#nullable disable

namespace Screamer.Presistance.Migrations
{
    [DbContext(typeof(ScreamerDbContext))]
    partial class ScreamerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cac43a6e-f7bb-4448-baaf-1add431ccbbf",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "cbc43a8e-f7bb-4445-baaf-1add431ffbbf",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "dbc43a8e-f7bb-4445-baaf-1999999999",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "cbc43a8e-f7bb-4445-baaf-1add431ffbbf"
                        },
                        new
                        {
                            UserId = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            RoleId = "cac43a6e-f7bb-4448-baaf-1add431ccbbf"
                        },
                        new
                        {
                            UserId = "9e224968-33e4-4652-b7b7-agfddsr",
                            RoleId = "dbc43a8e-f7bb-4445-baaf-1999999999"
                        },
                        new
                        {
                            UserId = "9e224968-33e4-4652-b7b7-ismailbentabett",
                            RoleId = "cbc43a8e-f7bb-4445-baaf-1add431ffbbf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Screamer.Domain.Common.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Avatar");
                });

            modelBuilder.Entity("Screamer.Domain.Common.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MoodId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectID")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "objectID");

                    b.Property<string>("PostImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoodId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Adress");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(700),
                            Name = "News",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(738)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(826),
                            Name = "Politics",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(826)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(827),
                            Name = "Science",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(833)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(834),
                            Name = "Technology",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(836)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(837),
                            Name = "Gaming",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(856)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(867),
                            Name = "Sports",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(867)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(868),
                            Name = "Music",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(869),
                            Name = "Movies",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(870)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(871),
                            Name = "Television",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(872)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(874),
                            Name = "Books",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(874)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(875),
                            Name = "Art",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(875)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(877),
                            Name = "Food",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(877)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(878),
                            Name = "Travel",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(879)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1053),
                            Name = "Fitness",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1053)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1054),
                            Name = "Health",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1062)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1078),
                            Name = "Fashion",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1079)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1079),
                            Name = "Relationships",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1080)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1082),
                            Name = "Advice",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1082)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1083),
                            Name = "Writing",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1083)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1084),
                            Name = "Photography",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1084)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1085),
                            Name = "DIY (Do-It-Yourself)",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1086)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1086),
                            Name = "Nature",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1087)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1088),
                            Name = "Animals",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1088)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1089),
                            Name = "Memes",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1089)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1090),
                            Name = "Funny",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1090)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1091),
                            Name = "Jokes",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1092)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1092),
                            Name = "History",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1093)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1094),
                            Name = "Philosophy",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1094)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1095),
                            Name = "Psychology",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1095)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1096),
                            Name = "Education",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1096)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1097),
                            Name = "Career",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1098)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1098),
                            Name = "Personal Finance",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1099)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1100),
                            Name = "Entrepreneurship",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1100)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1137),
                            Name = "Parenting",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1138)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1139),
                            Name = "Relationships",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1139)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1140),
                            Name = "Technology News",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1140)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1141),
                            Name = "Programming",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1142)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1143),
                            Name = "Web Development",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1143)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1144),
                            Name = "Data Science",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1144)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1145),
                            Name = "Cryptocurrency",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1145)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1146),
                            Name = "Design",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1146)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1147),
                            Name = "Gaming News",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1148)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1149),
                            Name = "PC Gaming",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1149)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1150),
                            Name = "Console Gaming",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1150)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1151),
                            Name = "Mobile Gaming",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1151)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1152),
                            Name = "Esports",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1152)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1153),
                            Name = "Music News",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1154)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1155),
                            Name = "Hip-Hop",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1155)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1156),
                            Name = "Rock",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1156)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1158),
                            Name = "Pop Culture",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1158)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1159),
                            Name = "Fitness Motivation",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1160)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1160),
                            Name = "Nutrition",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1161)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1162),
                            Name = "Weightlifting",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1162)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1163),
                            Name = "Yoga",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1163)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1164),
                            Name = "Running",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1164)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1165),
                            Name = "Cycling",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1165)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1166),
                            Name = "CrossFit",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1167)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1168),
                            Name = "Bodybuilding",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1168)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1169),
                            Name = "Productivity",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1169)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1170),
                            Name = "Self-improvement",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1170)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1171),
                            Name = "Meditation",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1171)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1172),
                            Name = "Mindfulness",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1173)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1173),
                            Name = "Motivation",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1174)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1175),
                            Name = "Self-care",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1175)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1176),
                            Name = "Cooking",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1176)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1178),
                            Name = "Baking",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1178)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1179),
                            Name = "Grilling",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1180)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1181),
                            Name = "Veganism",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1181)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1182),
                            Name = "Vegetarianism",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1182)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1183),
                            Name = "Meal Prep",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1183)
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1184),
                            Name = "Gardening",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1184)
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1185),
                            Name = "Home Improvement",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1186)
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1186),
                            Name = "Interior Design",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1187)
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1188),
                            Name = "Real Estate",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1188)
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1189),
                            Name = "Personal Finance Tips",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1189)
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1190),
                            Name = "Investing",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1190)
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1191),
                            Name = "Stock Market",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1192)
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1192),
                            Name = "Cryptocurrency Trading",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1193)
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1194),
                            Name = "Entrepreneur Stories",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1194)
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1195),
                            Name = "Startups",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1195)
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1196),
                            Name = "Small Business",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1196)
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1197),
                            Name = "Marketing",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1198)
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1198),
                            Name = "Social Media",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1199)
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1200),
                            Name = "Podcasts",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1200)
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1201),
                            Name = "Writing Prompts",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1201)
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1202),
                            Name = "Fantasy",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1202)
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1203),
                            Name = "Science Fiction",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1203)
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1205),
                            Name = "Horror",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1205)
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1206),
                            Name = "Thrillers",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1207)
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1208),
                            Name = "True Crime",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1208)
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1209),
                            Name = "Paranormal",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1209)
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1210),
                            Name = "Comics",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1210)
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1211),
                            Name = "Anime",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1211)
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1212),
                            Name = "Manga",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1212)
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1213),
                            Name = "Board Games",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1214)
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1215),
                            Name = "Card Games",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1215)
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1216),
                            Name = "Tabletop RPGs",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1216)
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1217),
                            Name = "Travel Photography",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1217)
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1218),
                            Name = "Outdoor Adventures",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1218)
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1219),
                            Name = "Celebrities",
                            UpdatedAt = new DateTime(2023, 6, 3, 16, 10, 55, 166, DateTimeKind.Local).AddTicks(1219)
                        });
                });

            modelBuilder.Entity("Screamer.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int?>("LatestMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("LatestMessageId");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.ChatRoomUser", b =>
                {
                    b.Property<int>("ChatroomId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("ChatroomId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatRoomUser");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("ReactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionId");

                    b.HasIndex("GroupName");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Cover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cover");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("PostTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MessageSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipientUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("MoodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostCategory", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("PostId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostHashtag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("HashtagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("PostId", "HashtagId");

                    b.HasIndex("HashtagId");

                    b.ToTable("PostHashtags");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostImage");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ReactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Discord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onlyfans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patreon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pinterest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reddit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snapchat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telegram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiktok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tumblr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Viber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Youtube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Social");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("PostTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Screamer.Domain.Follow", b =>
                {
                    b.Property<string>("SourceUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("SourceUserId", "TargetUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Screamer.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ObjectID")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "objectID");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df2f9169-d313-4792-a7c4-3d9f6d12f42b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDr5ycnneAxSTIBwkTKQhOEH6AscbSyKNCbP7oHI3AKa+u1TLc8EQQ4PgVsgGPNuvg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e7972a7-0702-4228-b63c-bf14121c116a",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8234cbac-2492-44be-8f32-37f5ffdd1aac",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEND38hB0ggzK5irvV5np0NHC7thjm9QK9S4OZ0FJ3WV9wlRK7F+l4X5uadx6na75HQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a757cb7f-1f44-43fd-a0d9-aee8a0d054ac",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "user"
                        },
                        new
                        {
                            Id = "9e224968-33e4-4652-b7b7-agfddsr",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75e2b341-169d-4708-9940-063bace54697",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mod@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Mod",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOD@LOCALHOST.COM",
                            NormalizedUserName = "MOD",
                            PasswordHash = "AQAAAAIAAYagAAAAEP2ag3Og/BtFG5WlRjMMoh+GnxHimpXtikSUY2yIi9RS5mu2CrhCLaK8Qhd3iQiYpg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb488147-8d26-4acc-a1f8-30951e65b02d",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "mod"
                        },
                        new
                        {
                            Id = "9e224968-33e4-4652-b7b7-ismailbentabett",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc435592-fdee-4d3f-82dc-2b321e326148",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ismailbentabett@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ismail",
                            LastName = "Bentabet",
                            LockoutEnabled = false,
                            NormalizedEmail = "ISMAILBENTABETT@GMAIL.COM",
                            NormalizedUserName = "ISMAILBENTABETT",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ6Mr9gtMhXwjXzli8If58Oflg+yNlsUPHYrVMcpXIzPrVL/e5SdH/zNgw2C6HkNEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0098d806-cbc5-42de-979b-e87f408bece4",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "ismailbentabett"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Screamer.Domain.Common.Avatar", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("Avatars")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Common.Post", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Mood", "Mood")
                        .WithMany("Posts")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.Navigation("Mood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Adress", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithOne("Adress")
                        .HasForeignKey("Screamer.Domain.Entities.Adress", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.ChatRoom", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Message", "LatestMessage")
                        .WithMany()
                        .HasForeignKey("LatestMessageId");

                    b.Navigation("LatestMessage");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.ChatRoomUser", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatRoomUsers")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("ChatRoomUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.CommentReaction", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Connection", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Group", null)
                        .WithMany("Connections")
                        .HasForeignKey("GroupName");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Cover", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("Covers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Mention", b =>
                {
                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("Mentions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("Mentions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Message", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostCategory", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("PostCategories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostHashtag", b =>
                {
                    b.HasOne("Screamer.Domain.Entities.Hashtag", "Hashtag")
                        .WithMany("PostHashtags")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("PostHashtags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.PostReaction", b =>
                {
                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Social", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithOne("Socials")
                        .HasForeignKey("Screamer.Domain.Entities.Social", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Screamer.Domain.Common.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Screamer.Domain.Follow", b =>
                {
                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "SourceUser")
                        .WithMany("Following")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Screamer.Identity.Models.ApplicationUser", "TargetUser")
                        .WithMany("Followers")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Screamer.Domain.Common.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Mentions");

                    b.Navigation("PostCategories");

                    b.Navigation("PostHashtags");

                    b.Navigation("PostImages");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Category", b =>
                {
                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatRoomUsers");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Group", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Hashtag", b =>
                {
                    b.Navigation("PostHashtags");
                });

            modelBuilder.Entity("Screamer.Domain.Entities.Mood", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Screamer.Identity.Models.ApplicationUser", b =>
                {
                    b.Navigation("Adress");

                    b.Navigation("Avatars");

                    b.Navigation("ChatRoomUsers");

                    b.Navigation("Covers");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Mentions");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("Posts");

                    b.Navigation("Socials");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
