# Stage 1: Build AngularUI
FROM node:14 AS angular-build
WORKDIR /app
COPY Screamer.AngularUI/package.json Screamer.AngularUI/package-lock.json ./
RUN npm ci
COPY Screamer.AngularUI .
RUN npm run build

# Stage 2: Build and publish .NET projects
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS dotnet-build
WORKDIR /src

# Copy and restore solution file
COPY Screamer.sln .
COPY **/*.csproj ./
RUN dotnet restore

# Copy the entire project and build
COPY . .
RUN dotnet publish -c Release -o /app

# Stage 3: Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=dotnet-build /app .
COPY --from=angular-build /app/dist ./wwwroot

# Set the entry point for the main application
ENTRYPOINT ["dotnet", "Screamer.WebApi.dll"]
