version: '3'
services:
  angular-ui:
    build:
      context: .
      dockerfile: Dockerfile-angular
    ports:
      - 4200:80
    volumes:
      - ./Screamer.AngularUI:/app

  web-api:
    build:
      context: .
      dockerfile: Dockerfile-dotnet
    ports:
      - 5000:80
    depends_on:
      - db
    volumes:
      - ./Screamer.WebApi:/app
    environment:
      - ConnectionStrings__DefaultConnection=Server=Server=localhost\\sqlexpress;Database=Screamer;Trusted_Connection=True ;MultipleActiveResultSets=true ;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=
